language: node_js
node_js:
  - "10"

cache: npm

script: npm run docs:build

after_script:
  - sh deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: master
