language: node_js
node_js:
  - "10"

cache: npm

script: npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m ":rocket: 自动部署"
  - git push --force --quiet "https://${$GITHUB_TOKEN}@${GH_REF}" master:${P_BRANCH}

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
target-branch: gh-pages
on:
  branch: master
