language: node_js
node_js:
  - "10"

cache: npm

after_script:
  - sh build/deploy-ci.sh

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
target-branch: gh-pages
on:
  branch: master
