language: node_js
node_js:
  - "10"

cache: npm

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
target-branch: gh-pages
on:
  branch: master
